### ISSUE TITLE
Create opam package for piqilib 0.6.11

### ISSUE THREAD

**Issue by trevorsummerssmith** [alavrik/piqi#48]
Hello,

Thanks for your great software! I don't know if this is the correct place to file this -- but I was wondering if you could create a 0.6.11 piqilib for opam? Due to the base64 upgrade there are now annoying conflicts with other packages that one would want to use piqilib with (for example ocaml-cohttp). I am happy to make a pull request as well if that is helpful.

Apologies if this is not the right place for this ticket.

Thanks.

Trevor

**Comment by alavrik** [comment]
Hey Trevor, thanks for letting me know! I'll submit the package some time later today. Perhaps should have pushed it earlier... It didn't occur to me that somebody may run into compatibility problems.

In the meantime you can use this repo for the latest piqi version: https://github.com/piqi/piqi-opam-repo -- I keep the up-to-date opam packaging scripts there. Or you can just pin the version directly from git.

**Comment by trevorsummerssmith** [comment]
Anton,

Thanks so much! I am currently using the repo for the latest. Just thought I'd pass it along as it will help with usability. Thanks again.

Trevor

**Comment by alavrik** [comment]
This is done now: https://github.com/ocaml/opam-repository/pull/3716
