### ISSUE TITLE
Unbound module Base64

### ISSUE THREAD

**Issue by ananthcm** [alavrik/piqi#53]
Im facing the error "unbound module Base64" while executing "make" command
Error: Unbound module Base64
make[3]: *** [piqi_base64.cmi] Error 2

**Comment by alavrik** [comment]
Which version are you using? Are you pulling dependencies using `opam` or `make deps`? There was a backward incompatible change in `base64` package -- they renamed base64 to b64 in a newer version. I bet the problem you are seeing is related to that.
