### ISSUE TITLE
OCaml 4.06 support

### ISSUE THREAD

**Issue by vbmithr** [alavrik/piqi#57]
Piqi cannot be used on 4.06 due to optcomp no longer supported :(

**Comment by alavrik** [comment]
Should be fixed now. I'll try to do a new release within a week. Thanks for letting me know!

**Comment by drvink** [comment]
I'd also appreciate it if a release could be made, as right now, people have to `opam pin` piqilib to its git repo in order to install piqi itself or anything that depends on piqilib on OCaml 4.06 due to the optcomp issue. (Apologies for the noise--just figured I'd say something as well.)

**Comment by vbmithr** [comment]
New release please!!

**Comment by sagotch** [comment]
Ping

**Comment by alavrik** [comment]
@sagotch @vbmithr @drvink thank you for reminding and apologies for more delays. Will get this done within a week. In the meantime, can you clarify the problems with using a version directly from master? This would help me to be more proactive and considerate when it comes to maintenance and releases.

**Comment by sagotch** [comment]
I think that version from master is okay. But it requires an extra step (opam pin) from people how want to use piqilib. Also, having a package which install without complication reassures people using it :)

For now, this lines in opam files solved the issue for me:
```
pin-depends: [
  [ "piqilib.dev" "git://github.com/alavrik/piqi" ]
  [ "piqi.dev" "git://github.com/alavrik/piqi-ocaml" ]
]
```

**Comment by alavrik** [comment]
all done, waiting for opam repo PR to be merged: https://github.com/ocaml/opam-repository/pull/12610

**Comment by alavrik** [comment]
it is now released in opam. closing.

**Comment by alavrik** [comment]
Turns out there was a problem in the opam spec that prevent the new version from installing correctly: https://github.com/alavrik/piqi-ocaml/issues/12  This should be fixed once merged in the upstream opam repo.
