### ISSUE TITLE
Switch from Ulex to something different?

### ISSUE THREAD

**Issue by XVilka** [alavrik/piqi#59]
Ulex is not updated for years and rely on Camlp4, which is dying. There are only two options - either update ulex itself, or switch to something more updated.

**Comment by alavrik** [comment]
Is there an actual problem? Ulex (and Camlp4) should be stable despite of not being updated, but there's always a risk of something breaking with newer releases.

Ultimately, I was planning to rewrite the the lexer either manually or using ocamllex. The language no longer allows unquoted utf8 so ulex is not really needed any more.

**Comment by XVilka** [comment]
For now not, not is a problem. Just was surprised to see camlp4 installing.
There is also [Sedlex](https://github.com/ocaml-community/sedlex), but I am not sure how it is maintained though.

**Comment by sagotch** [comment]
camlp4 does not install properly on travis with osx platform and 4.07 ocaml switch.

Then, it breaks my CI, and possibly my compilation under osx.

I see that a `ulex-camlp5` package is available, but I do not know if it would be simple to switch from `ulex` to this.

`camlp5` is still maintained by its author.

**Comment by alavrik** [comment]
@XVilka looks like this should now be resolved by switching to ulex-camlp5 thanks to @sagotch -- see #64 for details.
