### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by vbmithr** [alavrik/piqi#61]
So that it works out of the box with newer base64 library…

**Comment by XVilka** [comment]
Makes sense also to include the [support](https://github.com/alavrik/piqi/issues/62)/[make sure](https://github.com/alavrik/piqi/pull/63) it works with OCaml 4.08 for this release then.

**Comment by alavrik** [comment]
@XVilka will do. thank you

**Comment by XVilka** [comment]
@alavrik can you please make a new release with the sedlex port? And then it probably worth to close this issue.

**Comment by XVilka** [comment]
@alavrik any updates on this? Sorry for disturbing, but would be awesome to have this major change in the opam.

**Comment by XVilka** [comment]
@alavrik while you are on it, can you please craft a new release for opam?

**Comment by XVilka** [comment]
Thank you @alavrik! It was merged in the opam-repository master: https://github.com/ocaml/opam-repository/commit/448805afd685638070beff77a59b9bc467d99c0d

So this bug can finally be closed.

**Comment by alavrik** [comment]
wonderful. Thanks @XVilka
