### ISSUE TITLE
Port to Dune build system

### ISSUE THREAD

**Issue by XVilka** [alavrik/piqi#66]
[Dune](https://dune.build) is the new de-facto standard in OCaml world, greatly simplifying building, maintenance, vendoring, and developing the code. It would improve a lot of things in piqi.

**Comment by alavrik** [comment]
does dune support cross-compilation for windows?

**Comment by alavrik** [comment]
Should be easier now if anyone wants to take a shot at it. I have just removed dependency on camlp4/camlp5. I have also removed custom solution for building third-party dependencies. It is all managed by opam now.
