### ISSUE TITLE
release the dune-built piqi packages

### ISSUE THREAD

**Issue by ivg** [alavrik/piqi#72]
Now everything is ready to release the dune-built piqi (known in opam as piqilib) and piqi-ocaml (known in opam as piqi) to the upstream repository. I tested locally using our own opam-repository that everything works fine, i.e., the binaries are installed, the commands are present, the compiler works, and piqi can now be loaded in runtime using dynlink (or dune plugins) without any special effort. For your reference, here are the [piqilib][1] and [piqi][2] opam files. If they are okay, then what is left is to cut the release on both repos and I can make the PR to the upstream/opam-repository (you would prefer to do it yourself?). 

[1]: https://github.com/BinaryAnalysisPlatform/opam-repository/blob/piqi/packages/piqilib/piqilib.master/opam
[2]: https://github.com/BinaryAnalysisPlatform/opam-repository/blob/piqi/packages/piqi/piqi.master/opam

**Comment by alavrik** [comment]
hi @ivg, I've just cut new releases fro both piqi and piqi-ocaml. Can you help with the PR to the opam repo?

**Comment by ivg** [comment]
Sure, I am on it. Thanks for the release!

**Comment by ivg** [comment]
Here we go, it took me some time to grep through all reverse dependencies, but it looks like that my package is the only one that is broken :) 
https://github.com/ocaml/opam-repository/pull/21947
